bookings/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from .views import (BookingCreateView,
                    UserBookingListView,
                    BookingDetailView,
                    BookingUpdateView,
                    BookingDeleteView,
                    BookingAdminUpdateView,
                    )
from django.contrib.admin.views.decorators import staff_member_required

urlpatterns = [
    path('', views.home, name='home'),
    path('booking/admin_list', views.booking_admin_index, name='booking-admin-index'),
    path('booking/admin/<int:pk>/update', staff_member_required(BookingAdminUpdateView.as_view()),
         name='booking-admin-update'),
    path('booking/index', views.index, name='booking-index'),
    path('booking/new', BookingCreateView.as_view(), name='user-booking'),
    path('booking/<str:username>', UserBookingListView.as_view(), name='user-bookings'),
    path('booking/<int:pk>/', BookingDetailView.as_view(), name='booking-detail'),
    path('booking/<int:pk>/update', BookingUpdateView.as_view(), name='booking-update'),
    path('booking/<int:pk>/delete', BookingDeleteView.as_view(), name='booking-delete'),


    # path('about/', views.about, name='blog-about'),
]

sweepTheFloor/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from users import views as user_views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bookings.urls')),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('profile/address/new', user_views.AddressCreateView.as_view(), name='address-create'),
    path('profile/address/<int:pk>/delete', user_views.AddressDeleteView.as_view(), name='address-delete'),
    path('profile/address/<int:pk>/update', user_views.AddressUpdateView.as_view(), name='address-update'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password-reset/done',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('activate/<uidb64>/<token>/', user_views.ActivateAccountView.as_view(), name='activate'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookings/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from users.models import Address


class BookingStatus(models.Model):
    status_desc = models.TextField(blank=False, max_length=50)

    def __str__(self):
        return f'{self.status_desc}'


class Booking(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    booking_date = models.DateField()
    booking_time = models.TimeField()
    status = models.ForeignKey(BookingStatus, on_delete=models.CASCADE)
    address = models.ForeignKey(Address, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.username} Booking'

    def get_absolute_url(self):
        return reverse('booking-detail', kwargs={'pk': self.pk})





    

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from django.urls import reverse
from django.core.exceptions import ValidationError


class IdType(models.Model):
    id_type_desc = models.TextField(max_length=50)

    def __str__(self):
        return f'{self.id_type_desc} ID'


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')
    id_type = models.ForeignKey(IdType, on_delete=models.CASCADE, blank=True, null=True)
    id_no = models.TextField(max_length=50, blank=True, null=True)
    phone_no = models.TextField(max_length=15, blank=True, null=True)
    mobile_no = models.TextField(max_length=15, blank=True, null=True)

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)


class Country(models.Model):
    code = models.CharField(max_length=3)
    name = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.name}'


class State(models.Model):
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    state = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.state}'


class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    lot_no = models.CharField(max_length=15)
    street = models.CharField(max_length=50)
    locality = models.CharField(max_length=100, verbose_name='Locality Area or Housing/Apartment Area Name')
    postal_code = models.IntegerField()
    city = models.CharField(max_length=50)
    state = models.ForeignKey(State, on_delete=models.CASCADE)
    is_billing = models.BooleanField(default=False)
    is_primary = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.lot_no}, {self.street}, {self.locality}, {self.postal_code}, {self.city}, {self.state}'

    def save(self, *args, **kwargs):
        if self._state.adding:  # new record action
            if Address.objects.filter(is_primary=True, user=self.user).exists() == self.is_primary:
                raise ValidationError('Record with primary address already exists.'
                                      'Please uncheck the existing primary address')
            else:
                super(Address, self).save(*args, **kwargs)
        else:  # update record action
            if not self.is_primary:
                super(Address, self).save(*args, **kwargs)
            else:  # check if is primary record already exist
                if len(Address.objects.filter(is_primary=True, user=self.user)) > 0:
                    # updating the same record with primary address
                    if self.pk == Address.objects.filter(is_primary=True, user=self.user).first().pk:
                        super(Address, self).save(*args, **kwargs)
                    else:
                        raise ValidationError('Record with primary address already exists.'
                                              'Please uncheck the existing primary address')
                else:
                    super(Address, self).save(*args, **kwargs)

bookings/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from .models import Booking, BookingStatus
from parameters.models import ActivateBoolean, EmailList, EmailType
from users.models import Address
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import (CreateView,
                                  ListView,
                                  DetailView,
                                  UpdateView,
                                  DeleteView)
from getenv import env
from bootstrap_datepicker_plus import DatePickerInput, TimePickerInput
from .filters import BookingFilter
from django.core.paginator import Paginator
from mails.mailing import mail_to_user_booking, mail_to_admin_booking


def home(request):
    context = {
            # 'environ': os.environ.get('EMAIL_PASS')
            'environ': env("EMAIL_USER")
    }
    return render(request, 'bookings/home.html', context=context)


def index(request):
    bookings = Booking.objects.filter(user=request.user).order_by('-booking_date')
    my_filter = BookingFilter(request.GET, queryset=bookings)
    bookings = my_filter.qs

    paginator = Paginator(bookings, 5)
    page = request.GET.get('page')
    bookings = paginator.get_page(page)

    context = {
        'bookings': bookings,
        'my_filter': my_filter,
    }

    return render(request, 'bookings/index.html', context)


class BookingCreateView(LoginRequiredMixin, CreateView):

    model = Booking
    fields = ['booking_date', 'booking_time', 'address']

    def get_form(self):
        form = super().get_form()
        form.fields['booking_date'].widget = DatePickerInput()
        form.fields['booking_time'].widget = TimePickerInput()
        form.fields['address'].empty_label = 'Please select address'
        user_address = Address.objects.filter(user_id=self.request.user.id)
        form.fields['address'].queryset = user_address
        return form

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.status = BookingStatus.objects.filter(status_desc='Open').first()
        bookings = form.save()
        # send email notification
        user = User.objects.filter(id=self.request.user.id)
        param_email_user = ActivateBoolean.objects.filter()
        booking_id = bookings.id

        is_send_user = bool(ActivateBoolean.objects.values_list('activate',
                                                                flat=True).filter(
                                                                activation_type='send_to_user_email')[0])
        is_send_admin = bool(ActivateBoolean.objects.values_list('activate',
                                                                 flat=True).filter(
                                                                 activation_type='send_to_company_email')[0])

        if is_send_user:
            mail_to_user_booking(None,  # sender : set to none as sender default setup from system
                                 None,
                                 user[0].first_name,  # recipient_name
                                 user[0].email,  # user email
                                 'Booking Creation - Sweep The Floor',  # subject
                                 booking_id,
                                 bookings.status.status_desc,
                                 'new')   # record type
        if is_send_admin:
            mail_to_admin_booking(None,  # sender_email : set to none as sender default setup from system
                                  user[0].first_name,  # recipient_name
                                  'Booking Creation - Sweep The Floor',  # subject
                                  booking_id,
                                  'new')   # record type
        return super().form_valid(form)


class UserBookingListView(ListView):
    model = Booking
    template_name = 'bookings/index.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'bookings'
    # paginate_by = 3

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Booking.objects.filter(user=user).order_by('-booking_date')


class BookingDetailView(DetailView):
    model = Booking

    def get_context_data(self, **kwargs):
        context = super(BookingDetailView, self).get_context_data(**kwargs)
        status = BookingStatus.objects.filter(booking=self.get_object()).first()

        if status.status_desc == "Open":
            context['modify'] = 'enabled'
        else:
            context['modify'] = 'disabled'
            context['message'] = f'Booking status is now :  {status.status_desc}. '
        return context


class BookingUpdateView(LoginRequiredMixin, UpdateView):
    model = Booking
    fields = ['booking_date', 'booking_time', 'address']

    def get_form(self):
        form = super().get_form()
        form.fields['booking_date'].widget = DatePickerInput()
        form.fields['booking_time'].widget = TimePickerInput()
        form.fields['address'].empty_label = 'Please select address'
        return form

    def form_valid(self, form):
        form.instance.user = self.request.user
        bookings = form.save()
        # send email notification
        user = User.objects.filter(id=self.request.user.id)
        booking_id = bookings.id
        is_send_user = bool(ActivateBoolean.objects.values_list('activate',
                                                                flat=True).filter(
            activation_type='send_to_user_email')[0])

        if is_send_user:
            mail_to_user_booking(None,  # sender : set to none as sender default setup from system
                                 None,
                                 user[0].first_name,  # recipient_name
                                 user[0].email,  # user email
                                 'Booking Creation - Sweep The Floor',  # subject
                                 booking_id,
                                 bookings.status.status_desc,
                                 'update')  # record type
        return super().form_valid(form)

    def test_func(self):
        booking = self.get_object()
        if self.request.user == booking.user:
            return True
        return False


class BookingDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Booking
    success_url = '/'

    def test_func(self):
        booking = self.get_object()
        if self.request.user == booking.user:
            return True
        return False

# admin area


@user_passes_test(lambda u: u.is_staff)
def booking_admin_index(request):

    bookings = Booking.objects.all().order_by('-id')
    my_filter = BookingFilter(request.GET, queryset=bookings)
    bookings = my_filter.qs

    paginator = Paginator(bookings, 5)
    page = request.GET.get('page')
    bookings = paginator.get_page(page)

    context = {
        'bookings': bookings,
        'my_filter': my_filter,
    }

    return render(request, 'bookings/index.html', context)


class BookingAdminUpdateView(LoginRequiredMixin, UpdateView):
    permission_required = 'is_staff'
    model = Booking
    fields = ['booking_date', 'booking_time', 'address', 'status']
    template_name = 'bookings/booking_admin_edit.html'
    success_url = '/booking/admin_list'
    
    def get_form(self):
        form = super().get_form()
        form.fields['booking_date'].widget = DatePickerInput()
        form.fields['booking_time'].widget = TimePickerInput()
        form.fields['address'].empty_label = 'Please select address'
        form.fields['status'].empty_label = 'Please select status'
        # assign address related to user record
        booking = self.get_object()
        form.fields['address'].queryset = Address.objects.filter(user_id=booking.user)
        return form

    def form_valid(self, form):
        bookings = form.save()
        # send email notification
        user = User.objects.filter(id=bookings.user.id)  # get user of the booking record
        booking_id = bookings.id
        mail_to_user_booking(None,  # sender : set to none as sender default setup from system
                             'Admin',  # sender_name
                             user[0].first_name,  # recipient_name
                             user[0].email,  # user email
                             'Booking Status Update - Sweep The Floor',  # subject
                             booking_id,
                             bookings.status.status_desc,
                             'update')  # record type
        return super().form_valid(form)

bookings/templates/bookings/booking_admin_edit.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load crispy_forms_tags %}
<!--for bootstrap datetimepicker-->
{% block extrahead %}
{% bootstrap_javascript jquery='full' %}
{{ form.media }}
{% endblock %}
<!--end for bootstrap datetimepicker-->
{% block content %}


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Contact Info - {{object.user.first_name}}
                    {{object.user.last_name}}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <address class="content-section text-muted shadow-sm container-fluid padding">

                    <table class="text-muted">
                        <tr class="">
                            <td class=""><i class="fas fa-sign-in-alt"></i></td>
                            <td class="">{{ object.user.username}}</td>
                        </tr>
                        <tr class="">
                            <td class=""><i class="fas fa-phone"></i></td>
                            <td class="">{{ object.user.profile.phone_no}}</td>
                        </tr>
                        <tr class="">
                            <td class=""><i class="fas fa-mobile-alt"></td>
                            <td class="">{{ object.user.profile.mobile_no}}</td>
                        </tr>
                        <tr class="">
                            <td class=""><i class="fas fa-envelope"></i></td>
                            <td class="">{{ object.user.email}}</td>
                        </tr>
                    </table>
                </address>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

            </div>
        </div>
    </div>
</div>


<div class="content-section shadow">
    <form method="post" action="" class="">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Booking Administration</legend>
            <!-- Button trigger modal -->
            <a href="" class="btn btn-outline-info btn-lg" data-toggle="modal" data-target="#exampleModal">
                <i class="fas fa-id-card"></i>
            </a>
            <hr class="">
            <h2 class="h2"><i class="fas fa-edit"></i> Update Booking Record - {{object.id}} </h2>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Update</button>
        </div>
    </form>
</div>

{% endblock %}

bookings/templates/bookings/booking_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
    <div class="content-section">
        <form method="post" action="" class="">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Booking</legend>
                <h2 class="">Are you sure you want to delete the booking "{{object.booking_date}} at {{object.booking_time}} "?</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{%url 'booking-detail' object.id%}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

bookings/templates/bookings/booking_detail.html
{% extends 'base.html' %}
{% block content %}

<div class="content-section">
    <div class="media">
        <img class="img-thumbnail account-img" src="{{ user.profile.image.url }}">
        <div class="media-body">
            <h2 class="account-heading">{{ user.first_name }} {{ user.last_name}}</h2>
            <p class="text-secondary">{{ user.email }}</p>
        </div>

    </div>
    <div class="media-body">
        <div class="article-metadata">
            {% if modify == 'disabled' %}
            <p>
                <button class="btn btn-outline-danger" type="button" data-toggle="collapse" data-target="#message"
                        aria-expanded="false" aria-controls="message">
                    <i class="fas fa-exclamation-triangle"></i>
                </button>
            </p>
            <div class="collapse" id="message">
                <div class="card card-body text-danger border border-danger">
                    {{message}}
                </div>
                <br>
            </div>

            {% endif %}

            <div class="card mb-4">
            <h5 class="card-header">Booking Details For Booking ID: {{ object.id }}</h5>
            <div class="card-body">
                <dl class="row">
                <dt class="col-sm-3"><i class="fas fa-check-circle"></i></dt>
                <dd class="col-sm-9">{{ object.status.status_desc}}</dd>
                <dt class="col-sm-3"><i class="fas fa-calendar-alt"></i></dt>
                <dd class="col-sm-9">{{ object.booking_date|date:"F d, Y"}}</dd>
                <dt class="col-sm-3"><i class="far fa-clock"></i></dt>
                <dd class="col-sm-9">{{ object.booking_time}}</dd>
                <dt class="col-sm-3"><i class="fas fa-map-marker-alt"></i></dt>
                <dd class="col-sm-9">
                    <p class="">{{ object.address.lot_no}} {{ object.address.street}} ,</p>
                    <p class="">{{ object.address.locality}} , </p>
                    <p class="">{{ object.address.postal_code}} {{ object.address.city}} , </p>
                    <p class="">{{ object.address.state}} , {{ object.address.state.country}}</p>

                </dd>
            </dl>
            </div>
        </div>

            {% if object.user == user %}
            <div class="">
                <a href="{% url 'booking-update' object.id %}" class="btn btn-secondary btn-sm mt-1 mb-1 {{ modify }} ">Update</a>
                <a href="{% url 'booking-delete' object.id %}" class="btn btn-danger btn-sm mt-1 mb-1 {{ modify }} ">Delete</a>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

bookings/templates/bookings/booking_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
<!--for bootstrap datetimepicker-->
{% block extrahead %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{{ form.media }}
{% endblock %}
<!--end for bootstrap datetimepicker-->

{% block content %}

<div class="content-section">
    <div class="media">
        <img class="img-thumbnail account-img" src="{{ user.profile.image.url }}">
        <div class="media-body">
            <h2 class="account-heading">{{ user.username }}</h2>
            <p class="text-secondary">{{ user.email }}</p>
        </div>
    </div>
    <br><br>
    <form method="post" action="" class="">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Book Your Cleaning Services Today</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">

            {% if user.address_set.count == 0 %}
            <div class="">
                <h5 class="text text-warning">
                    <i class="fas fa-exclamation-triangle"></i>
                    <small class="text-muted">Address in empty. Please create an address</small>
                </h5>
            </div>



            <a href="{% url 'address-create' %}" class="btn btn-outline-dark btn-lg mt-1 mb-1"><i class="fas fa-map-marker-alt"></i> + Address</a>
            {%else%}
            <button class="btn btn-outline-info" type="submit">Book Now</button>
            {% endif%}

        </div>

    </form>
</div>

</div>


{% endblock %}

bookings/templates/bookings/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="jumbotron shadow">
    <h1 class="display-4">Welcome</h1>
    <p class="lead">SweepTheFloor is the online booking system for cleaning and pest control services. We are currently
        covering area in KL, Selangor and Putrajaya</p>
    <hr class="my-4">
    <p>We provide contract cleaning services and building maintenance plus pest control to enhance their working
        environment to ensure optimum output. Cleaning accessories are also provided mainly consist of chemicals and air
        refresher, dust control carpets and sanitary bin. We support government initiative to support for local industry
        by providing our products, services plus solutions to enhance their business operation.</p>
    <p class="">Register with us and book your cleaning service today!</p>
    {% if user.is_authenticated %}
    <a class="btn btn-outline-info btn-lg" href="{% url 'user-booking' %}" role="button">Book Now!</a>
    {% else %}
    <a class="btn btn-outline-info btn-lg" href="{% url 'register' %}" role="button">Register Now!</a>
    {% endif %}
    {% if user.is_authenticated == False %}
    <hr class="my-4">
    <div>
        <small class="text-muted">
            Already Have An Account? <a class="ml-2" href="{% url 'login' %}">Sign In</a>
        </small>
    </div>
    {% endif %}
</div>

<br>

<div class="card-deck">
    <div class="row">
        <div class="col-md-4">
            <div class="card shadow-sm" style="height: 30rem;">
                <img src="{% static 'website_resource/stf_card_img2_clean_office.png' %}" class="card-img-top"
                     alt="...">
                <div class="card-body overflow-auto">
                    <h5 class="card-title">Office</h5>
                    <p class="card-text">Cleaning office premises, clinics, warehouse, housing developers showrooms,
                        etc.</p>
                    <!--                    <a href="{% url 'user-booking' %}" class="btn btn-primary">Book Now!</a>-->
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card shadow-sm" style="height: 30rem;">
                <img src="{% static 'website_resource/stf_card_img1_clean_house.jpg' %}" class="card-img-top" alt="...">
                <div class="card-body overflow-auto">
                    <h5 class="card-title">House</h5>
                    <p class="card-text">Daily cleaning service to any housing area including apartments and
                        condominiums.</p>
                    <!--                    <a href="{% url 'user-booking' %}" class="btn btn-primary">Book Now!</a>-->
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card shadow-sm" style="height: 30rem;">
                <img src="{% static 'website_resource/stf_card_img3_pool.jpg' %}" class="card-img-top" alt="...">
                <div class="card-body overflow-auto">
                    <h5 class="card-title">Clubs</h5>
                    <p class="card-text">Swimming pool, gym, party rooms, lounge, meeting rooms, gaming area, function
                        suites, gardens etc.</p>
                    <!--                    <a href="{% url 'user-booking' %}" class="btn btn-primary">Book Now!</a>-->
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock%}